# This workflow will build and deploy the WAR app to Azure Web App - demobackend

name: Build and Deploy WAR app to Azure Web App - demobackend

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      # Checkout code from GitHub
      - uses: actions/checkout@v4

      # Set up Java version
      - name: Set up Java version
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'microsoft'

      # Build with Maven inside BankingApplication folder
      - name: Build with Maven
        working-directory: BankingApplication
        run: mvn clean install

      # Upload the WAR file for deployment
      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: java-app
          path: 'BankingApplication/target/*.war'

  deploy:
    runs-on: windows-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write

    steps:
      # Download the WAR artifact from the build job
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: java-app

      # Log in to Azure using Azure service principal credentials
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      # Deploy the WAR file to Azure Web App
      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'demobackend'
          slot-name: 'production'
          package: 'BankingApplication/target/*.war'
